### ISSUE TITLE
Please do not rely on `pytorch-cpu`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/htm-pytorch-feedstock#1]
The package `pytorch-cpu` is a compatibility output for the old naming used by the pytorch channel; it should not be used for various reasons. For one, we're planning to remove it, but more importantly, it uselessly restricts user choice (who might otherwise be able to install GPU-enabled `pytorch`.
https://github.com/conda-forge/htm-pytorch-feedstock/blob/2b00a1b987a9c2412f22066e7818486dc38c99b6/recipe/meta.yaml#L25

The solution is to rename this to `pytorch`, which can be satisfied by either the CPU or the CUDA variant, depending on what the user chooses resp. what his system allows.

**Comment by thewchan** [comment]
@h-vetinari I can make this change

**Comment by thewchan** [comment]
Resolved with https://github.com/conda-forge/htm-pytorch-feedstock/pull/2
